[package]
name = "bb-1"
version = "0.1.0"
authors = ["flame4 <646361781@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.32.0"